- name: Install MariaDB package (CentOS)
  tags: centos,db,mariadb
  yum:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "CentOS"

- name: Mariadb - Restarting/Enabling
  service:
    name: mariadb
    state: restarted
    enabled: true

- name: Instal MariaDB package (Ubuntu)
  tags: db, mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
